name: verobank
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.4
  intl: ^0.17.0
  uuid: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_generator: ^1.0.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true